# golang 1.16 recommended in README
FROM golang:1.16

WORKDIR /usr/src/app

COPY . .

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build && \ 
    useradd -m appuser && \
    chown appuser . && \
    rm -rf /go && \
    rm -rf /usr/local/go

USER appuser

CMD ["./server"]
