# Node version 16 recommended in the README
FROM node:16

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api/

RUN npm install && \
    npm install -g serve && \
    npm run build && \
    useradd -m appuser && \
    chown appuser . && \
    rm -rf node_modules

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
