services:

  frontend:
    image: example-frontend

  backend:
    image: example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db

  redis:
    image: redis:alpine

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
