FROM golang:alpine3.19

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build && \ 
    adduser -D appuser && \
    chown appuser . && \
    rm -rf /go && \
    rm -rf /usr/local/go

USER appuser

CMD ["./server"]
