# Node version 16 recommended in the README
FROM node:16-alpine3.16

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && \
    npm install -g serve && \
    npm run build && \
    adduser -D appuser && \
    chown appuser . && \
    rm -rf node_modules

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
