# We need Java 8
FROM amazoncorretto:8-alpine3.19 as build-stage

WORKDIR /usr/app

EXPOSE 8080

COPY . .

RUN ./mvnw package


FROM amazoncorretto:8-alpine3.19

WORKDIR /usr/app

COPY --from=build-stage /usr/app/target/docker-example-1.1.3.jar /usr/app/

CMD ["java", "-jar", "./docker-example-1.1.3.jar"]
