# Node version 16 recommended in the README
FROM node:16

EXPOSE 5001

WORKDIR /usr/src/app

COPY package* ./

RUN npm install

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api/

RUN npm install -g serve
RUN npm run build

RUN useradd -m appuser
RUN chown appuser .
USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
